### ISSUE TITLE
《High-Resolution Image Inpainting with Iterative Confidence Feedback and Guided Upsampling》

### ISSUE THREAD

**Issue by ray0809** [zengxianyu/906#1]
您好，
    不好意思打扰了，我叫曾锐，之前给您qq和谷歌邮箱都发过邮件，你可能没看到，我想问下您那篇eccv的关于修复的文章的补充材料能否发一份给我，我想了解这个修复网络的更加细节的地方。
    感谢！

**Comment by zengxianyu** [comment]
Hi Zengrui,

I am sorry for the late reply. I have been very busy these days. Here's the supplementary file: 

https://maildluteducn-my.sharepoint.com/:b:/g/personal/zengyu_mail_dlut_edu_cn/EbQvnHMGlmFIoS2qmNnwOdwBgpIrTS26NNrFy8JB9jeS_Q?e=Vcy6mj

The code might be released after being approved by Adobe. My collaborators are working on that. If you are interested in the inpainting results, you can try the web app or call the API (see https://zengxianyu.github.io/iic/#api for details). If you are interested in the implementation, please refer to  https://github.com/jiahuiyu/generative_inpainting. The code of our method is largely inspired by this repo and most implementation details are the same as it. 

Best,
Yu
